-- Migration: Alter contracts.status to include 'to_sign' and rename active label mapping handled on frontend

-- Try to drop existing autogenerated CHECK constraint if it exists
DO $$
BEGIN
  BEGIN
    ALTER TABLE contracts DROP CONSTRAINT contracts_status_check;
  EXCEPTION WHEN undefined_object THEN
    -- constraint might have a different autogenerated name; try to find and drop it dynamically
    PERFORM 1;
  END;
END$$;

-- Add a new named CHECK constraint with extended set
ALTER TABLE contracts
  ADD CONSTRAINT contracts_status_check
  CHECK (status IN ('draft','to_sign','active','archived','cancelled'));


